[2022-05-18 23:52:19,086] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-18 23:52:19,105] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-18 23:52:19,106] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:52:19,107] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-05-18 23:52:19,108] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:52:19,129] {taskinstance.py:1262} INFO - Executing <Task(GreatExpectationsOperator): great_expectations_sources.sources.jaffle_shop__orders> on 2022-05-17 23:51:54.527642+00:00
[2022-05-18 23:52:19,148] {standard_task_runner.py:52} INFO - Started process 260 to run task
[2022-05-18 23:52:19,162] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'great_expectations_sources.sources.jaffle_shop__orders', 'scheduled__2022-05-17T23:51:54.527642+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpjxog42bg', '--error-file', '/tmp/tmpr5vtzw7f']
[2022-05-18 23:52:19,164] {standard_task_runner.py:77} INFO - Job 247: Subtask great_expectations_sources.sources.jaffle_shop__orders
[2022-05-18 23:52:19,268] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-05-17T23:51:54.527642+00:00 [running]> on host 41cba24e2fbb
[2022-05-18 23:52:19,428] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=great_expectations_sources.sources.jaffle_shop__orders
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T23:51:54.527642+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T23:51:54.527642+00:00
[2022-05-18 23:52:19,431] {great_expectations.py:122} INFO - Running validation with Great Expectations...
[2022-05-18 23:52:19,433] {great_expectations.py:125} INFO - Ensuring data context is valid...
[2022-05-18 23:52:21,794] {sqlalchemy_execution_engine.py:404} WARNING - schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
[2022-05-18 23:52:21,799] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:135 DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
[2022-05-18 23:52:24,044] {validator.py:1669} INFO - 	15 expectation(s) included in expectation_suite.
[2022-05-18 23:52:24,415] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-05-18 23:52:24,418] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-05-18 23:52:24,442] {logging_mixin.py:109} WARNING - Calculating Metrics:   6%|6         | 2/33 [00:00<00:00, 81.46it/s]
[2022-05-18 23:52:24,548] {logging_mixin.py:109} WARNING - Calculating Metrics:  12%|#2        | 4/33 [00:00<00:00, 30.57it/s]
[2022-05-18 23:52:24,555] {logging_mixin.py:109} WARNING - Calculating Metrics:  12%|#2        | 4/33 [00:00<00:00, 30.57it/s]
[2022-05-18 23:52:24,696] {logging_mixin.py:109} WARNING - Calculating Metrics:  36%|###6      | 12/33 [00:00<00:00, 45.79it/s]
[2022-05-18 23:52:24,700] {logging_mixin.py:109} WARNING - Calculating Metrics:  36%|###6      | 12/33 [00:00<00:00, 45.79it/s]
[2022-05-18 23:52:24,865] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 66.82it/s]
[2022-05-18 23:52:24,870] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 66.82it/s]
[2022-05-18 23:52:24,944] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 66.82it/s]
[2022-05-18 23:52:24,979] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 66.82it/s]
[2022-05-18 23:52:24,982] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 58.46it/s]
[2022-05-18 23:52:24,983] {logging_mixin.py:109} WARNING - 
[2022-05-18 23:52:31,729] {great_expectations.py:197} INFO - Validation with Great Expectations successful.
[2022-05-18 23:52:31,804] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=great_expectations_sources.sources.jaffle_shop__orders, execution_date=20220517T235154, start_date=20220518T235219, end_date=20220518T235231
[2022-05-18 23:52:31,928] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-18 23:52:32,127] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
