[2022-05-18 23:52:47,960] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_compile scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-18 23:52:47,975] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_compile scheduled__2022-05-17T23:51:54.527642+00:00 [queued]>
[2022-05-18 23:52:47,976] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:52:47,977] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-05-18 23:52:47,978] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 23:52:47,994] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_validate.dbt_compile> on 2022-05-17 23:51:54.527642+00:00
[2022-05-18 23:52:48,009] {standard_task_runner.py:52} INFO - Started process 307 to run task
[2022-05-18 23:52:48,019] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'dbt_validate.dbt_compile', 'scheduled__2022-05-17T23:51:54.527642+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmp_g5sfcpq', '--error-file', '/tmp/tmpgxoxmny5']
[2022-05-18 23:52:48,020] {standard_task_runner.py:77} INFO - Job 251: Subtask dbt_validate.dbt_compile
[2022-05-18 23:52:48,132] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.dbt_validate.dbt_compile scheduled__2022-05-17T23:51:54.527642+00:00 [running]> on host 41cba24e2fbb
[2022-05-18 23:52:48,298] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=dbt_validate.dbt_compile
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T23:51:54.527642+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T23:51:54.527642+00:00
[2022-05-18 23:52:48,305] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-18 23:52:48,307] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        dbt compile --profiles-dir /opt/dbt/jaffle_shop --project-dir /opt/dbt/jaffle_shop\n        ']
[2022-05-18 23:52:48,340] {subprocess.py:85} INFO - Output:
[2022-05-18 23:52:55,386] {subprocess.py:89} INFO - 23:52:55  Running with dbt=1.1.0
[2022-05-18 23:52:55,601] {subprocess.py:89} INFO - 23:52:55  Found 5 models, 13 tests, 0 snapshots, 0 analyses, 170 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2022-05-18 23:52:55,619] {subprocess.py:89} INFO - 23:52:55
[2022-05-18 23:52:55,810] {subprocess.py:89} INFO - 23:52:55  Concurrency: 1 threads (target='dev')
[2022-05-18 23:52:55,814] {subprocess.py:89} INFO - 23:52:55
[2022-05-18 23:52:56,872] {subprocess.py:89} INFO - 23:52:56  Done.
[2022-05-18 23:52:57,976] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-18 23:52:58,036] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=dbt_validate.dbt_compile, execution_date=20220517T235154, start_date=20220518T235247, end_date=20220518T235258
[2022-05-18 23:52:58,138] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-18 23:52:58,281] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
