[2022-05-18 22:37:43,244] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__customers scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 22:37:43,276] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__customers scheduled__2022-05-17T22:12:00.138285+00:00 [queued]>
[2022-05-18 22:37:43,278] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 22:37:43,280] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-05-18 22:37:43,282] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-18 22:37:43,310] {taskinstance.py:1262} INFO - Executing <Task(GreatExpectationsOperator): great_expectations_sources.sources.jaffle_shop__customers> on 2022-05-17 22:12:00.138285+00:00
[2022-05-18 22:37:43,337] {standard_task_runner.py:52} INFO - Started process 595 to run task
[2022-05-18 22:37:43,390] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'great_expectations_sources.sources.jaffle_shop__customers', 'scheduled__2022-05-17T22:12:00.138285+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpnqvb4drt', '--error-file', '/tmp/tmp6671sofs']
[2022-05-18 22:37:43,393] {standard_task_runner.py:77} INFO - Job 118: Subtask great_expectations_sources.sources.jaffle_shop__customers
[2022-05-18 22:37:43,565] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__customers scheduled__2022-05-17T22:12:00.138285+00:00 [running]> on host 3db539bd1596
[2022-05-18 22:37:43,716] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=great_expectations_sources.sources.jaffle_shop__customers
AIRFLOW_CTX_EXECUTION_DATE=2022-05-17T22:12:00.138285+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-17T22:12:00.138285+00:00
[2022-05-18 22:37:43,720] {great_expectations.py:122} INFO - Running validation with Great Expectations...
[2022-05-18 22:37:43,722] {great_expectations.py:125} INFO - Ensuring data context is valid...
[2022-05-18 22:37:48,457] {sqlalchemy_execution_engine.py:404} WARNING - schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
[2022-05-18 22:37:48,539] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:135 DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
[2022-05-18 22:37:50,899] {validator.py:1669} INFO - 	13 expectation(s) included in expectation_suite.
[2022-05-18 22:37:51,667] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/30 [00:00<?, ?it/s]
[2022-05-18 22:37:51,672] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/30 [00:00<?, ?it/s]
[2022-05-18 22:37:51,708] {logging_mixin.py:109} WARNING - Calculating Metrics:   7%|6         | 2/30 [00:00<00:00, 55.28it/s]
[2022-05-18 22:37:51,893] {logging_mixin.py:109} WARNING - Calculating Metrics:  13%|#3        | 4/30 [00:00<00:01, 18.05it/s]
[2022-05-18 22:37:51,896] {logging_mixin.py:109} WARNING - Calculating Metrics:  13%|#3        | 4/30 [00:00<00:01, 18.05it/s]
[2022-05-18 22:37:51,964] {logging_mixin.py:109} WARNING - Calculating Metrics:  40%|####      | 12/30 [00:00<00:00, 18.05it/s]
[2022-05-18 22:37:52,054] {logging_mixin.py:109} WARNING - Calculating Metrics:  80%|########  | 24/30 [00:00<00:00, 72.25it/s]
[2022-05-18 22:37:52,063] {logging_mixin.py:109} WARNING - Calculating Metrics:  80%|########  | 24/30 [00:00<00:00, 72.25it/s]
[2022-05-18 22:37:52,337] {logging_mixin.py:109} WARNING - Calculating Metrics:  93%|#########3| 28/30 [00:00<00:00, 72.25it/s]
[2022-05-18 22:37:52,409] {logging_mixin.py:109} WARNING - Calculating Metrics:  97%|#########6| 29/30 [00:00<00:00, 72.25it/s]
[2022-05-18 22:37:53,797] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 30/30 [00:02<00:00, 72.25it/s]
[2022-05-18 22:37:53,908] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 30/30 [00:02<00:00, 72.25it/s]
[2022-05-18 22:37:53,911] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 30/30 [00:02<00:00, 13.40it/s]
[2022-05-18 22:37:53,915] {logging_mixin.py:109} WARNING - 
[2022-05-18 22:38:00,959] {great_expectations.py:197} INFO - Validation with Great Expectations successful.
[2022-05-18 22:38:01,018] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=great_expectations_sources.sources.jaffle_shop__customers, execution_date=20220517T221200, start_date=20220518T223743, end_date=20220518T223801
[2022-05-18 22:38:01,209] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-18 22:38:01,309] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
