[2022-06-04 20:40:04,287] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 20:40:04,320] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 20:40:04,321] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 20:40:04,322] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-06-04 20:40:04,323] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 20:40:04,342] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily> on 2022-06-03 02:56:49.432006+00:00
[2022-06-04 20:40:04,351] {standard_task_runner.py:52} INFO - Started process 1260 to run task
[2022-06-04 20:40:04,364] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily', 'scheduled__2022-06-03T02:56:49.432006+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpictvynno', '--error-file', '/tmp/tmptkuv_1pa']
[2022-06-04 20:40:04,365] {standard_task_runner.py:77} INFO - Job 313: Subtask dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily
[2022-06-04 20:40:04,425] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily scheduled__2022-06-03T02:56:49.432006+00:00 [running]> on host 0c1ca7618279
[2022-06-04 20:40:04,497] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T02:56:49.432006+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-03T02:56:49.432006+00:00
[2022-06-04 20:40:04,499] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-04 20:40:04,501] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt --no-write-json test --target dev --select assert_positive_total_for_payments_daily --profiles-dir /opt/dbt/jaffle_shop --project-dir /opt/dbt/jaffle_shop --vars \'{"date": " 2022-06-03 " }\'']
[2022-06-04 20:40:04,524] {subprocess.py:85} INFO - Output:
[2022-06-04 20:40:09,995] {subprocess.py:89} INFO - 20:40:09  Running with dbt=1.1.0
[2022-06-04 20:40:10,191] {subprocess.py:89} INFO - 20:40:10  Found 5 models, 14 tests, 0 snapshots, 0 analyses, 170 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2022-06-04 20:40:10,198] {subprocess.py:89} INFO - 20:40:10
[2022-06-04 20:40:10,378] {subprocess.py:89} INFO - 20:40:10  Concurrency: 1 threads (target='dev')
[2022-06-04 20:40:10,380] {subprocess.py:89} INFO - 20:40:10
[2022-06-04 20:40:10,405] {subprocess.py:89} INFO - 20:40:10  1 of 1 START test assert_positive_total_for_payments_daily ..................... [RUN]
[2022-06-04 20:40:10,535] {subprocess.py:89} INFO - 20:40:10  1 of 1 PASS assert_positive_total_for_payments_daily ........................... [[32mPASS[0m in 0.13s]
[2022-06-04 20:40:10,629] {subprocess.py:89} INFO - 20:40:10
[2022-06-04 20:40:10,632] {subprocess.py:89} INFO - 20:40:10  Finished running 1 test in 0.43s.
[2022-06-04 20:40:10,638] {subprocess.py:89} INFO - 20:40:10
[2022-06-04 20:40:10,640] {subprocess.py:89} INFO - 20:40:10  [32mCompleted successfully[0m
[2022-06-04 20:40:10,642] {subprocess.py:89} INFO - 20:40:10
[2022-06-04 20:40:10,644] {subprocess.py:89} INFO - 20:40:10  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-06-04 20:40:11,850] {subprocess.py:93} INFO - Command exited with return code 0
[2022-06-04 20:40:11,895] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=dbt_test.test.jaffle_shop.assert_positive_total_for_payments_daily, execution_date=20220603T025649, start_date=20220604T204004, end_date=20220604T204011
[2022-06-04 20:40:11,964] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-04 20:40:12,060] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
