[2022-06-04 02:56:56,644] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 02:56:56,662] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-06-03T02:56:49.432006+00:00 [queued]>
[2022-06-04 02:56:56,664] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 02:56:56,665] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2022-06-04 02:56:56,666] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-04 02:56:56,690] {taskinstance.py:1262} INFO - Executing <Task(GreatExpectationsOperator): great_expectations_sources.sources.jaffle_shop__orders> on 2022-06-03 02:56:49.432006+00:00
[2022-06-04 02:56:56,705] {standard_task_runner.py:52} INFO - Started process 937 to run task
[2022-06-04 02:56:56,717] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'model_level_dbt_great_expectations_dag', 'great_expectations_sources.sources.jaffle_shop__orders', 'scheduled__2022-06-03T02:56:49.432006+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/model_level_dbt_great_expectations_dag.py', '--cfg-path', '/tmp/tmpvcxce6fd', '--error-file', '/tmp/tmpgh_2s6fp']
[2022-06-04 02:56:56,719] {standard_task_runner.py:77} INFO - Job 198: Subtask great_expectations_sources.sources.jaffle_shop__orders
[2022-06-04 02:56:56,785] {logging_mixin.py:109} INFO - Running <TaskInstance: model_level_dbt_great_expectations_dag.great_expectations_sources.sources.jaffle_shop__orders scheduled__2022-06-03T02:56:49.432006+00:00 [running]> on host 3d17a0db806e
[2022-06-04 02:56:56,894] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=luciano.naveiro
AIRFLOW_CTX_DAG_ID=model_level_dbt_great_expectations_dag
AIRFLOW_CTX_TASK_ID=great_expectations_sources.sources.jaffle_shop__orders
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T02:56:49.432006+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-03T02:56:49.432006+00:00
[2022-06-04 02:56:56,897] {great_expectations.py:122} INFO - Running validation with Great Expectations...
[2022-06-04 02:56:56,898] {great_expectations.py:125} INFO - Ensuring data context is valid...
[2022-06-04 02:56:58,653] {sqlalchemy_execution_engine.py:404} WARNING - schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
[2022-06-04 02:56:58,663] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:135 DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
[2022-06-04 02:57:00,835] {validator.py:1669} INFO - 	15 expectation(s) included in expectation_suite.
[2022-06-04 02:57:01,012] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-06-04 02:57:01,014] {logging_mixin.py:109} WARNING - Calculating Metrics:   0%|          | 0/33 [00:00<?, ?it/s]
[2022-06-04 02:57:01,027] {logging_mixin.py:109} WARNING - Calculating Metrics:   6%|6         | 2/33 [00:00<00:00, 153.85it/s]
[2022-06-04 02:57:01,066] {logging_mixin.py:109} WARNING - Calculating Metrics:  12%|#2        | 4/33 [00:00<00:00, 75.79it/s] 
[2022-06-04 02:57:01,112] {logging_mixin.py:109} WARNING - Calculating Metrics:  36%|###6      | 12/33 [00:00<00:00, 122.05it/s]
[2022-06-04 02:57:01,198] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 146.57it/s]
[2022-06-04 02:57:01,199] {logging_mixin.py:109} WARNING - Calculating Metrics:  82%|########1 | 27/33 [00:00<00:00, 146.57it/s]
[2022-06-04 02:57:01,286] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 146.57it/s]
[2022-06-04 02:57:01,343] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 146.57it/s]
[2022-06-04 02:57:01,353] {logging_mixin.py:109} WARNING - Calculating Metrics: 100%|##########| 33/33 [00:00<00:00, 97.18it/s] 
[2022-06-04 02:57:01,354] {logging_mixin.py:109} WARNING - 
[2022-06-04 02:57:05,244] {great_expectations.py:197} INFO - Validation with Great Expectations successful.
[2022-06-04 02:57:05,293] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=model_level_dbt_great_expectations_dag, task_id=great_expectations_sources.sources.jaffle_shop__orders, execution_date=20220603T025649, start_date=20220604T025656, end_date=20220604T025705
[2022-06-04 02:57:05,384] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-04 02:57:05,484] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
