[2022-05-15 15:24:21,293] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: models_dbt_dag.dbt_run.model.jaffle_shop.fct_customer_orders scheduled__2022-05-14T15:15:58.068711+00:00 [queued]>
[2022-05-15 15:24:21,312] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: models_dbt_dag.dbt_run.model.jaffle_shop.fct_customer_orders scheduled__2022-05-14T15:15:58.068711+00:00 [queued]>
[2022-05-15 15:24:21,314] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 15:24:21,315] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2022-05-15 15:24:21,317] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 15:24:21,340] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): dbt_run.model.jaffle_shop.fct_customer_orders> on 2022-05-14 15:15:58.068711+00:00
[2022-05-15 15:24:21,350] {standard_task_runner.py:52} INFO - Started process 9827 to run task
[2022-05-15 15:24:21,357] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'models_dbt_dag', 'dbt_run.model.jaffle_shop.fct_customer_orders', 'scheduled__2022-05-14T15:15:58.068711+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/models_dbt_dag.py', '--cfg-path', '/tmp/tmpxe2pyje4', '--error-file', '/tmp/tmpqmi1dbvi']
[2022-05-15 15:24:21,359] {standard_task_runner.py:77} INFO - Job 165: Subtask dbt_run.model.jaffle_shop.fct_customer_orders
[2022-05-15 15:24:21,446] {logging_mixin.py:109} INFO - Running <TaskInstance: models_dbt_dag.dbt_run.model.jaffle_shop.fct_customer_orders scheduled__2022-05-14T15:15:58.068711+00:00 [running]> on host b0833397c3cf
[2022-05-15 15:24:21,526] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=models_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run.model.jaffle_shop.fct_customer_orders
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T15:15:58.068711+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T15:15:58.068711+00:00
[2022-05-15 15:24:21,529] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-15 15:24:21,531] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt --no-write-json run --target dev --models fct_customer_orders --profiles-dir /opt/***/dags/jaffle_shop --project-dir /opt/***/dags/jaffle_shop']
[2022-05-15 15:24:21,552] {subprocess.py:85} INFO - Output:
[2022-05-15 15:24:24,917] {subprocess.py:89} INFO - 15:24:24  Running with dbt=1.1.0
[2022-05-15 15:24:25,036] {subprocess.py:89} INFO - 15:24:25  Found 5 models, 13 tests, 0 snapshots, 0 analyses, 170 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2022-05-15 15:24:25,042] {subprocess.py:89} INFO - 15:24:25
[2022-05-15 15:24:25,195] {subprocess.py:89} INFO - 15:24:25  Concurrency: 1 threads (target='dev')
[2022-05-15 15:24:25,201] {subprocess.py:89} INFO - 15:24:25
[2022-05-15 15:24:25,222] {subprocess.py:89} INFO - 15:24:25  1 of 1 START table model dev.fct_customer_orders ............................... [RUN]
[2022-05-15 15:24:25,500] {subprocess.py:89} INFO - 15:24:25  1 of 1 OK created table model dev.fct_customer_orders .......................... [[32mSELECT 99[0m in 0.27s]
[2022-05-15 15:24:25,556] {subprocess.py:89} INFO - 15:24:25
[2022-05-15 15:24:25,559] {subprocess.py:89} INFO - 15:24:25  Finished running 1 table model in 0.51s.
[2022-05-15 15:24:25,566] {subprocess.py:89} INFO - 15:24:25
[2022-05-15 15:24:25,571] {subprocess.py:89} INFO - 15:24:25  [32mCompleted successfully[0m
[2022-05-15 15:24:25,574] {subprocess.py:89} INFO - 15:24:25
[2022-05-15 15:24:25,577] {subprocess.py:89} INFO - 15:24:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-05-15 15:24:26,658] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-15 15:24:26,689] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=models_dbt_dag, task_id=dbt_run.model.jaffle_shop.fct_customer_orders, execution_date=20220514T151558, start_date=20220515T152421, end_date=20220515T152426
[2022-05-15 15:24:26,720] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-15 15:24:26,816] {local_task_job.py:264} INFO - 13 downstream tasks scheduled from follow-on schedule check
