[2022-05-15 03:11:15,471] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.jaffle_shop.stg_jaffle_shop__customers manual__2022-05-15T03:11:14.036092+00:00 [queued]>
[2022-05-15 03:11:15,484] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.jaffle_shop.stg_jaffle_shop__customers manual__2022-05-15T03:11:14.036092+00:00 [queued]>
[2022-05-15 03:11:15,485] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 03:11:15,486] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-15 03:11:15,487] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 03:11:15,506] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): model.jaffle_shop.stg_jaffle_shop__customers> on 2022-05-15 03:11:14.036092+00:00
[2022-05-15 03:11:15,512] {standard_task_runner.py:52} INFO - Started process 4198 to run task
[2022-05-15 03:11:15,527] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.jaffle_shop.stg_jaffle_shop__customers', 'manual__2022-05-15T03:11:14.036092+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp3_utp3zy', '--error-file', '/tmp/tmp5eff4vjx']
[2022-05-15 03:11:15,532] {standard_task_runner.py:77} INFO - Job 82: Subtask model.jaffle_shop.stg_jaffle_shop__customers
[2022-05-15 03:11:15,614] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.model.jaffle_shop.stg_jaffle_shop__customers manual__2022-05-15T03:11:14.036092+00:00 [running]> on host b0833397c3cf
[2022-05-15 03:11:15,713] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.jaffle_shop.stg_jaffle_shop__customers
AIRFLOW_CTX_EXECUTION_DATE=2022-05-15T03:11:14.036092+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-15T03:11:14.036092+00:00
[2022-05-15 03:11:15,718] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-15 03:11:15,723] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            cd /opt/***/dags/jaffle_shop &&\n            dbt --no-write-json run --target prod --models stg_jaffle_shop__customers --profiles-dir .\n            ']
[2022-05-15 03:11:15,747] {subprocess.py:85} INFO - Output:
[2022-05-15 03:11:19,977] {subprocess.py:89} INFO - 03:11:19  Running with dbt=1.1.0
[2022-05-15 03:11:20,225] {subprocess.py:89} INFO - 03:11:20  Unable to do partial parsing because config vars, config profile, or config target have changed
[2022-05-15 03:11:20,228] {subprocess.py:89} INFO - 03:11:20  Unable to do partial parsing because profile has changed
[2022-05-15 03:11:20,236] {subprocess.py:89} INFO - 03:11:20  Unable to do partial parsing because env vars used in profiles.yml have changed
[2022-05-15 03:11:22,048] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Did not find matching node for patch with name 'stg_customers' in the 'models' section of file 'models/staging/jaffle_shop/stg_jaffle_shop.yml'
[2022-05-15 03:11:22,053] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Did not find matching node for patch with name 'stg_orders' in the 'models' section of file 'models/staging/jaffle_shop/stg_jaffle_shop.yml'
[2022-05-15 03:11:22,192] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.assert_positive_total_for_payments' (tests/assert_positive_total_for_payments.sql) depends on a node named 'stg_payments' which was not found
[2022-05-15 03:11:22,194] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.unique_stg_customers_customer_id.c7614daada' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_customers' which was not found
[2022-05-15 03:11:22,197] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.not_null_stg_customers_customer_id.e2cfb1f9aa' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_customers' which was not found
[2022-05-15 03:11:22,199] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.unique_stg_orders_order_id.e3b841c71a' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_orders' which was not found
[2022-05-15 03:11:22,201] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.not_null_stg_orders_order_id.81cfe2fe64' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_orders' which was not found
[2022-05-15 03:11:22,204] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.accepted_values_stg_orders_status__completed__shipped__returned__return_pending__placed.89a0a7d5f1' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_orders' which was not found
[2022-05-15 03:11:22,205] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.relationships_stg_orders_customer_id__customer_id__ref_stg_customers_.430bf21500' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_customers' which was not found
[2022-05-15 03:11:22,208] {subprocess.py:89} INFO - 03:11:22  [[33mWARNING[0m]: Test 'test.jaffle_shop.relationships_stg_orders_customer_id__customer_id__ref_stg_customers_.430bf21500' (models/staging/jaffle_shop/stg_jaffle_shop.yml) depends on a node named 'stg_orders' which was not found
[2022-05-15 03:11:22,274] {subprocess.py:89} INFO - 03:11:22  Found 5 models, 4 tests, 0 snapshots, 0 analyses, 170 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2022-05-15 03:11:22,286] {subprocess.py:89} INFO - 03:11:22
[2022-05-15 03:11:22,560] {subprocess.py:89} INFO - 03:11:22  Concurrency: 1 threads (target='prod')
[2022-05-15 03:11:22,567] {subprocess.py:89} INFO - 03:11:22
[2022-05-15 03:11:22,596] {subprocess.py:89} INFO - 03:11:22  1 of 1 START view model analytics.stg_jaffle_shop__customers ................... [RUN]
[2022-05-15 03:11:22,894] {subprocess.py:89} INFO - 03:11:22  1 of 1 OK created view model analytics.stg_jaffle_shop__customers .............. [[32mCREATE VIEW[0m in 0.29s]
[2022-05-15 03:11:22,941] {subprocess.py:89} INFO - 03:11:22
[2022-05-15 03:11:22,943] {subprocess.py:89} INFO - 03:11:22  Finished running 1 view model in 0.65s.
[2022-05-15 03:11:22,960] {subprocess.py:89} INFO - 03:11:22
[2022-05-15 03:11:22,964] {subprocess.py:89} INFO - 03:11:22  [32mCompleted successfully[0m
[2022-05-15 03:11:22,967] {subprocess.py:89} INFO - 03:11:22
[2022-05-15 03:11:22,969] {subprocess.py:89} INFO - 03:11:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-05-15 03:11:24,565] {subprocess.py:93} INFO - Command exited with return code 0
[2022-05-15 03:11:24,628] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=model.jaffle_shop.stg_jaffle_shop__customers, execution_date=20220515T031114, start_date=20220515T031115, end_date=20220515T031124
[2022-05-15 03:11:24,688] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-15 03:11:24,791] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
